management:
  endpoint:
    shutdown:
      enabled: true
app:
  security:
    jwt:
      secret: K19zAxleDWjrdh58ZTTGQzyX0hzrs3j0DSVpyi+xFqI7f1oBhpELNP4nnAebAquKKn/KgDJB1t/FT6MDJT8LpQ==
      token-validity-in-seconds: 86400
      token-validity-in-seconds-remember-me: 2592000

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=LEGACY;DATABASE_TO_UPPER=false
    username: user
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
      path: /h2